# Generated by Django 5.1 on 2024-10-31 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiradas',
            fields=[
                ('id_retirada', models.AutoField(primary_key=True, serialize=False)),
                ('data_retirada', models.DateTimeField()),
                ('status_retirada', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluída', 'Concluída')], default='Retirada', max_length=50, null=True)),
                ('motivo_retirada', models.CharField(choices=[('TCC', 'Trabalho de Conclusão de Curso'), ('Aula', 'Aula'), ('Projetos', 'Projetos')], max_length=50)),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bem', models.IntegerField()),
                ('data_retirada', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_limite', models.DateTimeField()),
                ('status_retirada', models.CharField(choices=[('Retirado', 'Retirado'), ('Atrasado', 'Atrasado'), ('Devolvido', 'Devolvido')], default='Retirada', max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_retirada', to='bem.bem')),
                ('id_retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_retirada', to='retiradas.retiradas')),
            ],
        ),
    ]
