# Generated by Django 5.1 on 2024-10-10 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiradas',
            fields=[
                ('id_retirada', models.AutoField(primary_key=True, serialize=False)),
                ('data_retirada', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_limite', models.DateTimeField()),
                ('quantidade_bem', models.IntegerField()),
                ('motivo_retirada', models.CharField(choices=[('TCC', 'Trabalho de Conclusão de Curso'), ('Aula', 'Aula')], max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
