# Generated by Django 5.1 on 2024-10-31 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0001_initial'),
        ('retiradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itensretirada',
            unique_together={('id_retirada', 'id_bem')},
        ),
    ]
