# Generated by Django 5.1 on 2024-10-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0004_alter_bem_created_by'),
        ('retiradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bem', models.IntegerField()),
                ('id_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_retirada', to='bem.bem')),
                ('id_retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_retirada', to='retiradas.retiradas')),
            ],
        ),
    ]
