# Generated by Django 5.1 on 2024-10-31 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiradas', '0002_alter_itensretirada_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensretirada',
            name='id',
        ),
        migrations.AlterField(
            model_name='itensretirada',
            name='id_retirada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='itens_retirada', serialize=False, to='retiradas.retiradas'),
        ),
    ]
