# Generated by Django 5.1 on 2024-10-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiradas', '0002_itensretirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradas',
            name='motivo_retirada',
            field=models.CharField(choices=[('TCC', 'Trabalho de Conclusão de Curso'), ('Aula', 'Aula'), ('Projetos', 'Projetos')], max_length=50),
        ),
    ]
