# Generated by Django 5.1 on 2024-12-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiradas', '0003_remove_itensretirada_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensretirada',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itensretirada',
            name='id_retirada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_retirada', to='retiradas.retiradas'),
        ),
    ]
