# Generated by Django 5.1 on 2024-11-05 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bem', '0002_bem_quantidade_bem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateTimeField()),
                ('data_validade_reserva', models.DateTimeField()),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensReserva',
            fields=[
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='itens_reserva', serialize=False, to='reservas.reserva')),
                ('quantidade_bem', models.IntegerField()),
                ('data_reserva', models.DateTimeField()),
                ('data_validade_reserva', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_reserva', to='bem.bem')),
            ],
            options={
                'unique_together': {('id_reserva', 'id_bem')},
            },
        ),
    ]
