# Generated by Django 5.1 on 2024-09-07 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBem',
            fields=[
                ('id_tipo_bem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_bem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_bem',
            },
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_bem', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('permite_reserva', models.BooleanField(null=True)),
                ('id_status_bem', models.CharField(choices=[('R', 'Retirado'), ('D', 'Disponível')], default='D', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('id_tipo_bem', models.ForeignKey(db_column='id_tipo_bem', on_delete=django.db.models.deletion.CASCADE, to='bem.tipobem')),
            ],
            options={
                'db_table': 'bem',
            },
        ),
    ]
