# Generated by Django 5.1 on 2024-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='id_bem',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
