# Generated by Django 5.1 on 2024-11-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='quantidade_bem',
            field=models.IntegerField(default=1),
        ),
    ]
