# Generated by Django 5.1 on 2024-09-07 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0002_alter_bem_id_bem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bem',
            old_name='id_status_bem',
            new_name='status_bem',
        ),
        migrations.AlterField(
            model_name='bem',
            name='id_bem',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
