# Generated by Django 5.1 on 2024-12-10 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0002_bem_quantidade_bem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='quantidade_bem',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bem.bem')),
            ],
        ),
    ]
