# Generated by Django 5.1 on 2024-12-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0003_alter_bem_quantidade_bem_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='quantidade_bem',
            field=models.IntegerField(default=1),
        ),
    ]
