# Generated by Django 5.1 on 2024-10-31 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id_tipo_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pessoa', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_pessoa',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('id_tipo_pessoa', models.ForeignKey(db_column='id_tipo_pessoa', on_delete=django.db.models.deletion.CASCADE, to='core.tipopessoa')),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
    ]
