# Generated by Django 5.1 on 2024-09-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRetirada',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motivo_retirada',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id_tipo_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pessoa', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_pessoa',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_tipo_bem', models.ForeignKey(blank=True, db_column='id_tipo_bem', null=True, on_delete=django.db.models.deletion.CASCADE, to='bem.tipobem')),
            ],
            options={
                'db_table': 'kit',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateField()),
                ('data_validade_reserva', models.DateField(blank=True, null=True)),
                ('quantidade_bem', models.IntegerField(blank=True, null=True)),
                ('id_pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id_retirada', models.AutoField(primary_key=True, serialize=False)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('quantidade_bem', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_motivo_retirada', models.ForeignKey(db_column='id_motivo_retirada', on_delete=django.db.models.deletion.CASCADE, to='core.motivoretirada')),
                ('id_pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'db_table': 'retirada',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_tipo_pessoa',
            field=models.ForeignKey(db_column='id_tipo_pessoa', on_delete=django.db.models.deletion.CASCADE, to='core.tipopessoa'),
        ),
        migrations.CreateModel(
            name='ItensReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bem', models.IntegerField(blank=True, null=True)),
                ('id_bem', models.ForeignKey(db_column='id_bem', on_delete=django.db.models.deletion.CASCADE, to='bem.bem')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
            options={
                'db_table': 'itens_reserva',
                'unique_together': {('id_reserva', 'id_bem')},
            },
        ),
        migrations.CreateModel(
            name='ItensRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bem', models.IntegerField(blank=True, null=True)),
                ('id_bem', models.ForeignKey(db_column='id_bem', on_delete=django.db.models.deletion.CASCADE, to='bem.bem')),
                ('id_retirada', models.ForeignKey(db_column='id_retirada', on_delete=django.db.models.deletion.CASCADE, to='core.retirada')),
            ],
            options={
                'db_table': 'itens_retirada',
                'unique_together': {('id_retirada', 'id_bem')},
            },
        ),
    ]
