# Generated by Django 5.1 on 2024-10-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itensretirada',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itensretirada',
            name='id_bem',
        ),
        migrations.RemoveField(
            model_name='itensretirada',
            name='id_retirada',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='id_tipo_bem',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='id_motivo_retirada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_pessoa',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='id_pessoa',
        ),
        migrations.DeleteModel(
            name='ItensReserva',
        ),
        migrations.DeleteModel(
            name='ItensRetirada',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='MotivoRetirada',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Retirada',
        ),
    ]
